version: '3'
services:
  redis:
    image: redis:alpine

  web:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "3000:3000"
    depends_on: [redis]
    environment:
      REDIS_URL: redis://redis:6379
  
